# Schema for the configuration files of the Custom about us module.
custom_about_us.settings:
  type: config_object
  label: 'Custom about us settings'
  mapping:
    example:
      type: string
      label: 'Example'
